### ISSUE TITLE
does not work with object spread operator

### ISSUE THREAD

**Issue by piotr-s-brainhub** [timruffles/js-todos#4]
* *OS*: Max OS X 10.12.6
* *Node.js*: 8.9.4
* *npm*: 5.2.0
* *esprima*: 4.0.0
* *js-todos*: 1.1.0

js-todos does not handle object spread operators.

code:
```js
const x = { foo: 'foo-1', bar: 'bar-1' };
const y = { ...x, baz: 'baz-1' };

console.log({ x, y });
```

Expected output:
```
PASSED scanned 1 file, no todos found
```

Actual output:
```
Error processing 1.js:Error: Line 2: Unexpected token ...
```

**Comment by oprogramador** [comment]
It's fixed in https://github.com/timruffles/js-todos/pull/5
