### ISSUE TITLE
no-warning-comments eslint rule

### ISSUE THREAD

**Issue by piotr-s-brainhub** [timruffles/js-todos#7]
Using this eslint rule https://eslint.org/docs/2.0.0/rules/no-warning-comments is much better than this tool (js-todos) because:
- it detects todos in case-insensitive way
- I don't have to remember to run `js-todos` (I run eslint very often)

**Comment by timruffles** [comment]
Probably lots of things better than lots of things. Not sure there’s much
point opening issues about them though? 😂😂
